---
labels:
  - color: 0ffa16
    description: Indicates a PR has been approved by an approver from all required OWNERS files.
    name: approved
    target: prs
    prowPlugin: approve
    addedBy: approvers
  - color: e22a1f
    description: Indicates that a PR Looks Good to Someone
    name: lgtm
    target: prs
    addedBy: humans
  - color: e22aff
    description: Indicates that a PR needs OK from project members to run tests on
    name: needs-ok-to-test
    target: prs
    addedBy: humans
  - color: e222ff
    description: Indicates that a PR got OK from project members to run tests on
    name: ok-to-test
    target: prs
    addedBy: humans
  - color: ddaa00
    description: Denotes a PR that should be squashed by tide when it merges.
    name: merge-method-squash
    target: prs
    addedBy: humans
  - color: ffdd00
    description: Denotes a PR that should be rebased by tide when it merges.
    name: merge-method-rebase
    target: prs
    addedBy: humans
  - color: ffaadd
    description: Denotes a PR that should use a standard merge by tide when it merges.
    name: merge-method-merge
    target: prs
    addedBy: humans

