plugins:
  radochm:
    plugins:
    - approve
    - assign
    - blunderbuss
    - help
    - hold
    - invalidcommitmsg
    - label
    - lgtm
    - sigmention
    - trigger
    - verify-owners
    - wip
    - skip
    - transfer-issue
    - lifecycle
    - override
    - owners-label
  radochm/prow-infra:
    plugins:
    - cat
    - config-updater
    - dog
    
external_plugins:
  radochm:
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request

config_updater:
  maps:
    config/prow/config.yaml:
      name: config
      namespace: prow
    config/prow/plugins.yaml:
      name: plugins
      namespace: prow
    config/prow/jobs/**/*.yaml:
      name: job-config
      namespace: prow
    config/prow/labels.yaml:
      name: labels
      namespace: prow

approve:
  - repos:
     - radochm/build-test
    require_self_approval: true
    
label:
  additional_labels:
    - merge-method-merge
    - merge-method-rebase
    - merge-method-squash
