plugins:
  radochm:
    plugins:
    - approve
    - assign
    - blunderbuss
    - help
    - hold
    - invalidcommitmsg
    - label
    - lgtm
    - sigmention
    - trigger
    - verify-owners
    - wip
    - skip
    - transfer-issue
    - lifecycle
    - override
    - owners-label
  radochm/prow-infra:
    plugins:
    - cat
    - config-updater
    - dog
    
external_plugins:
  radochm:
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request

config_updater:
  maps:
    config/prow/config.yaml:
      name: config
      namespace: prow
    config/prow/plugins.yaml:
      name: plugins
      namespace: prow
    config/prow/jobs/**/*.yaml:
      name: job-config
      namespace: prow
    config/prow/labels.yaml:
      name: label-config
      namespace: prow

triggers:
  - repos:
      - build-test
    trusted_apps:
      - dependabot
    only_org_members: true
    ignore_ok_to_test: true
lgtm:
  - repos:
      - build-test
    review_acts_as_lgtm: true

